### ISSUE TITLE
[feat]: Make FMC log headers sticky

### ISSUE THREAD

**Issue by Guy-Adler** [GeoFS-Extensions/autoland#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, when scrolling the FMC log tab, the headers are scrolled out of view. I think we should make it so the headers stay at the top, to make it easier to identify columns.

**Comment by Guy-Adler** [comment]
This should do it:
```css
div.fmc-log-container th {
	text-align: left;
	top: 0;
	position: sticky;
	background-color: #fff;
	z-index: 10;
}
```
